services:
  - type: web
    name: cidion-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn src.api.app:create_app --factory --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /api/health
