name: Deploy to Render

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test health endpoint
      run: |
        python -c "
        import sys
        sys.path.append('.')
        from src.api.app import create_app
        app = create_app()
        print('✅ App created successfully')
        "
    
    # Auto-deploy happens via Render's GitHub integration
    - name: Deployment Status
      run: echo "🚀 Deployment will be handled by Render automatically"
